# This file was generated by GoReleaser. DO NOT EDIT.
class Remic < Formula
  desc ""
  homepage "https://github.com/knqyf263/remic"
  url "https://github.com/knqyf263/remic/releases/download/v0.0.2/remic_0.0.2_macOS-64bit.tar.gz"
  version "0.0.2"
  sha256 "76f3853e91a77f80e707d2e678cf542c6ac0cbca8325ab33a1cf3f6546e722aa"
  
  depends_on "rpm"

  def install
    bin.install "remic"
  end

  test do
    system "#{bin}/program --version"
  end
end
